"""Placeholder adapter for the interactive walkthrough before core integration.

This adapter does not implement OVERSEE logic. It only records scenario-aligned
paper-facing outputs so the presenter layer can be validated before connecting
to the existing OVERSEE execution paths.
"""

from __future__ import annotations

from demo.interactive_walkthrough.demo_state import DemoRunState
from demo.interactive_walkthrough.output_manager import write_json


def record_expected_layer_output(state: DemoRunState, layer_id: str) -> dict[str, str]:
    """Record the expected layer output from the selected scenario."""
    output_summary = state.scenario.expected_layer_outputs[layer_id]
    state.record_layer_output(layer_id, output_summary)

    artifact = {
        "scenario_id": state.scenario.scenario_id,
        "layer_id": layer_id,
        "mode": "presentation_placeholder",
        "note": (
            "This artifact is generated by the interactive demo presentation layer. "
            "It will be replaced by real OVERSEE layer outputs in the next steps."
        ),
        "expected_output_summary": output_summary,
    }

    path = state.output_dir / f"{layer_id}_presentation_placeholder.json"
    write_json(path, artifact)
    state.record_artifact(f"{layer_id}_placeholder", path)

    return artifact
