"""
Synthetic case schema for the Digital Factory scenario generator.

This module defines the first stable, deterministic case structure used to
generate industrial synthetic scenarios for testing the OVERSEE.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any, Literal


DecisionPosture = Literal[
    "controlled_monitoring",
    "constrained_execution",
    "diagnostic_review",
]

AssetFamily = Literal["compressor"]
SignalConsistency = Literal["consistent", "partially_consistent", "conflicting"]
DataQuality = Literal["good", "mixed", "poor"]
ProductionPressure = Literal["low", "moderate", "high"]
SparePartStatus = Literal["available", "delayed", "unknown"]


@dataclass(frozen=True)
class AssetContext:
    """Industrial asset context used by a synthetic scenario."""

    asset_id: str
    asset_type: AssetFamily
    criticality: str
    location: str
    production_dependency: str
    maintenance_history_summary: str


@dataclass(frozen=True)
class SensorEvidence:
    """Structured sensor evidence for the simulated asset."""

    vibration_mm_s: float
    temperature_c: float
    pressure_bar: float
    current_draw_a: float
    alarm_count_24h: int
    signal_consistency: SignalConsistency


@dataclass(frozen=True)
class PredictiveAlert:
    """Predictive model output used as decision evidence."""

    alert_type: str
    predicted_failure_mode: str
    time_to_failure_hours: int
    confidence_score: float
    model_uncertainty: str
    supporting_signals: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class OperationalContext:
    """Production and operational context around the case."""

    production_pressure: ProductionPressure
    shift: str
    demand_urgency: str
    downtime_window: str
    line_dependency: str
    customer_impact: str


@dataclass(frozen=True)
class MaintenanceContext:
    """Maintenance execution context and constraints."""

    spare_part_status: SparePartStatus
    spare_part_eta_hours: int | None
    technician_available: bool
    maintenance_window_available: bool
    workaround_available: bool
    inspection_required: bool


@dataclass(frozen=True)
class UncertaintyContext:
    """Diagnostic uncertainty and data quality context."""

    data_quality: DataQuality
    conflicting_evidence: bool
    diagnosis_clarity: str
    model_confidence_comment: str


@dataclass(frozen=True)
class NarrativeContext:
    """Textual scenario context. Deterministic in this first version."""

    technician_note: str
    supervisor_note: str
    maintenance_log_excerpt: str
    shift_handover_note: str


@dataclass(frozen=True)
class ExpectedDecision:
    """Expected decision interpretation used for evaluation."""

    expected_decision_posture: DecisionPosture
    expected_review_focus: str
    expected_human_review_required: bool
    expectation_rationale: str


@dataclass(frozen=True)
class GenerationMetadata:
    """Metadata explaining how the synthetic scenario was generated."""

    generator_name: str
    generator_version: str
    generation_mode: str
    uses_generative_ai: bool
    scenario_family: str
    scenario_variant: str


@dataclass(frozen=True)
class SyntheticDecisionCase:
    """Complete synthetic decision case generated by the Digital Factory."""

    case_id: str
    scenario_family: str
    asset_context: AssetContext
    sensor_evidence: SensorEvidence
    predictive_alert: PredictiveAlert
    operational_context: OperationalContext
    maintenance_context: MaintenanceContext
    uncertainty_context: UncertaintyContext
    narrative_context: NarrativeContext
    expected_decision: ExpectedDecision
    generation_metadata: GenerationMetadata

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-serializable dictionary representation."""
        return asdict(self)


