"""
Validated loader for Digital Factory synthetic scenario JSON files.

This module reads synthetic scenarios generated by the Digital Factory and
performs lightweight structural validation before future bridge/oversee use.

It intentionally does not:
- call generative AI;
- invoke the OVERSEE;
- modify deterministic anchor;
- modify priority logic.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


REQUIRED_TOP_LEVEL_FIELDS = {
    "case_id",
    "scenario_family",
    "asset_context",
    "sensor_evidence",
    "predictive_alert",
    "operational_context",
    "maintenance_context",
    "uncertainty_context",
    "narrative_context",
    "expected_decision",
    "generation_metadata",
}

REQUIRED_EXPECTED_DECISION_FIELDS = {
    "expected_decision_posture",
    "expected_review_focus",
    "expected_human_review_required",
    "expectation_rationale",
}

REQUIRED_GENERATION_METADATA_FIELDS = {
    "generator_name",
    "generator_version",
    "generation_mode",
    "uses_generative_ai",
    "scenario_family",
    "scenario_variant",
}

SUPPORTED_DECISION_POSTURES = {
    "controlled_monitoring",
    "constrained_execution",
    "diagnostic_review",
}


class SyntheticScenarioValidationError(ValueError):
    """Raised when a synthetic scenario file does not match the expected shape."""


def load_synthetic_scenarios(path: Path) -> list[dict[str, Any]]:
    """
    Load and validate a Digital Factory synthetic scenario JSON file.

    Args:
        path: JSON file path.

    Returns:
        A list of validated scenario dictionaries.

    Raises:
        FileNotFoundError: If the input file does not exist.
        SyntheticScenarioValidationError: If the file content is not valid.
    """
    if not path.exists():
        raise FileNotFoundError(f"Synthetic scenario file not found: {path}")

    raw_text = path.read_text(encoding="utf-8")

    try:
        payload = json.loads(raw_text)
    except json.JSONDecodeError as exc:
        raise SyntheticScenarioValidationError(
            f"Synthetic scenario file is not valid JSON: {path}"
        ) from exc

    if not isinstance(payload, list):
        raise SyntheticScenarioValidationError(
            "Synthetic scenario file must contain a list of scenarios."
        )

    if not payload:
        raise SyntheticScenarioValidationError(
            "Synthetic scenario file must contain at least one scenario."
        )

    for index, scenario in enumerate(payload):
        validate_synthetic_scenario(scenario, index=index)

    return payload


def validate_synthetic_scenario(scenario: Any, index: int = 0) -> None:
    """
    Validate one synthetic scenario dictionary.

    The validation is intentionally structural and conservative.
    It checks that the generated file can be safely consumed by later pipeline steps.
    """
    if not isinstance(scenario, dict):
        raise SyntheticScenarioValidationError(
            f"Scenario at index {index} must be a dictionary."
        )

    missing_top_level = REQUIRED_TOP_LEVEL_FIELDS - set(scenario.keys())
    if missing_top_level:
        raise SyntheticScenarioValidationError(
            f"Scenario at index {index} is missing top-level fields: "
            f"{sorted(missing_top_level)}"
        )

    _validate_expected_decision(scenario, index=index)
    _validate_generation_metadata(scenario, index=index)


def _validate_expected_decision(scenario: dict[str, Any], index: int) -> None:
    expected_decision = scenario.get("expected_decision")

    if not isinstance(expected_decision, dict):
        raise SyntheticScenarioValidationError(
            f"Scenario at index {index} must contain an expected_decision object."
        )

    missing_fields = REQUIRED_EXPECTED_DECISION_FIELDS - set(expected_decision.keys())
    if missing_fields:
        raise SyntheticScenarioValidationError(
            f"Scenario at index {index} is missing expected_decision fields: "
            f"{sorted(missing_fields)}"
        )

    posture = expected_decision.get("expected_decision_posture")
    if posture not in SUPPORTED_DECISION_POSTURES:
        raise SyntheticScenarioValidationError(
            f"Scenario at index {index} has unsupported expected decision posture: {posture}"
        )


def _validate_generation_metadata(scenario: dict[str, Any], index: int) -> None:
    generation_metadata = scenario.get("generation_metadata")

    if not isinstance(generation_metadata, dict):
        raise SyntheticScenarioValidationError(
            f"Scenario at index {index} must contain a generation_metadata object."
        )

    missing_fields = REQUIRED_GENERATION_METADATA_FIELDS - set(generation_metadata.keys())
    if missing_fields:
        raise SyntheticScenarioValidationError(
            f"Scenario at index {index} is missing generation_metadata fields: "
            f"{sorted(missing_fields)}"
        )

    if generation_metadata.get("generation_mode") != "deterministic":
        raise SyntheticScenarioValidationError(
            f"Scenario at index {index} must be deterministic in this phase."
        )

    if generation_metadata.get("uses_generative_ai") is not False:
        raise SyntheticScenarioValidationError(
            f"Scenario at index {index} must not use generative AI in this phase."
        )


